export const CS_FOLD = 'CS_FOLD';
export const CS_CHECK = 'CS_CHECK';
export const CS_CALL = 'CS_CALL';
export const CS_RAISE = 'CS_RAISE';
export const WINNER = 'WINNER';
export const CS_FETCH_LOBBY_INFO = 'CS_FETCH_LOBBY_INFO';
export const SC_RECEIVE_LOBBY_INFO = 'SC_RECEIVE_LOBBY_INFO';
export const SC_PLAYERS_UPDATED = 'SC_PLAYERS_UPDATED';
export const CS_JOIN_TABLE = 'CS_JOIN_TABLE';
export const SC_TABLE_JOINED = 'SC_TABLE_JOINED';
export const CS_LEAVE_TABLE = 'CS_LEAVE_TABLE';
export const SC_TABLE_LEFT = 'SC_TABLE_LEFT';
export const SC_TABLES_UPDATED = 'SC_TABLES_UPDATED';
export const SC_TABLE_UPDATED = 'SC_TABLE_UPDATED';
export const TABLE_MESSAGE = 'TABLE_MESSAGE';         // no emit event
export const CS_REBUY = 'CS_REBUY';
export const CS_SIT_DOWN = 'CS_SIT_DOWN';
export const CS_STAND_UP = 'CS_STAND_UP';
export const SITTING_OUT = 'SITTING_OUT';         // no emit event
export const SITTING_IN = 'SITTING_IN';         // no emit event
export const CS_DISCONNECT = 'CS_DISCONNECT';
